'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CalendarDays, Send } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';

type Leave = { id: string; type: 'PAID' | 'SICK' | 'UNPAID'; start_date: string; end_date: string; remarks: string | null; status: 'PENDING' | 'APPROVED' | 'REJECTED'; admin_comment: string | null };
const badge = (status: Leave['status']) => status === 'APPROVED' ? 'success' : status === 'REJECTED' ? 'danger' : 'warning';

export default function LeavesPage() {
  const [requests, setRequests] = useState<Leave[]>([]);
  const [form, setForm] = useState({ type: 'PAID', start_date: '', end_date: '', remarks: '' });
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); const response = await fetch('/api/leave-requests'); const result = await response.json(); if (response.ok) setRequests(result.requests); else setMessage(result.error); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); const response = await fetch('/api/leave-requests', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const result = await response.json(); if (!response.ok) setMessage(result.error); else { setMessage('Leave request submitted.'); setForm({ type: 'PAID', start_date: '', end_date: '', remarks: '' }); void load(); } };
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-surface-900">Leave requests</h1><p className="text-sm text-surface-500">Apply for time away and track approval status.</p></div><form onSubmit={submit} className="rounded-2xl border border-surface-200 bg-white p-6 shadow-card space-y-4"><h2 className="font-bold text-surface-900 flex items-center gap-2"><CalendarDays className="w-5 h-5 text-brand-600" /> New request</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><label className="text-sm text-surface-600">Type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="mt-1 w-full rounded-lg border border-surface-200 px-3 py-2"><option value="PAID">Paid</option><option value="SICK">Sick</option><option value="UNPAID">Unpaid</option></select></label><label className="text-sm text-surface-600">Start date<input required type="date" value={form.start_date} onChange={(event) => setForm({ ...form, start_date: event.target.value })} className="mt-1 w-full rounded-lg border border-surface-200 px-3 py-2" /></label><label className="text-sm text-surface-600">End date<input required type="date" value={form.end_date} onChange={(event) => setForm({ ...form, end_date: event.target.value })} className="mt-1 w-full rounded-lg border border-surface-200 px-3 py-2" /></label></div><label className="block text-sm text-surface-600">Remarks<textarea value={form.remarks} onChange={(event) => setForm({ ...form, remarks: event.target.value })} className="mt-1 w-full rounded-lg border border-surface-200 px-3 py-2" rows={3} /></label><Button type="submit" variant="primary" leftIcon={<Send className="w-4 h-4" />}>Submit request</Button>{message && <p className="text-sm text-surface-600">{message}</p>}</form><div className="rounded-2xl border border-surface-200 bg-white shadow-card overflow-hidden"><div className="p-5 border-b border-surface-100"><h2 className="font-bold text-surface-900">My requests</h2></div>{loading ? <p className="p-6 text-sm text-surface-500">Loading requests...</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-surface-50 text-left text-xs text-surface-500"><tr><th className="p-4">Type</th><th className="p-4">Dates</th><th className="p-4">Status</th><th className="p-4">Admin comment</th></tr></thead><tbody>{requests.map((request) => <tr key={request.id} className="border-t border-surface-100"><td className="p-4">{request.type}</td><td className="p-4">{request.start_date} to {request.end_date}</td><td className="p-4"><Badge variant={badge(request.status)}>{request.status}</Badge></td><td className="p-4 text-surface-600">{request.admin_comment || '—'}</td></tr>)}</tbody></table></div>}</div></div>;
}
