'use client';

import { ChangeEvent, ReactNode, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Camera, LockKeyhole, Mail, Phone, Shield } from 'lucide-react';
import { FormattedProfile } from '@/types/profile';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { createClient } from '@/lib/supabase/client';
import { formatCurrency, formatDate, getInitials } from '@/lib/utils';

type Tab = 'resume' | 'private' | 'salary' | 'security';
interface ProfileViewProps { profile: FormattedProfile; backHref?: string; backLabel?: string; }

export function ProfileView({ profile, backHref = '/dashboard/employee', backLabel = 'Back to Dashboard' }: ProfileViewProps) {
  const supabase = createClient();
  const [tab, setTab] = useState<Tab>('resume');
  const [payroll, setPayroll] = useState<{ basic_salary: number; allowances: number; deductions: number } | null>(null);
  const [newPassword, setNewPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [message, setMessage] = useState('');
  useEffect(() => { void fetch('/api/payroll/me').then((response) => response.ok ? response.json() : { payroll: null }).then((result) => setPayroll(result.payroll)); }, []);
  const basic = payroll?.basic_salary ?? profile.salaryStructure.baseSalary;
  const allowances = payroll?.allowances ?? profile.salaryStructure.allowances;
  const deductions = payroll?.deductions ?? profile.salaryStructure.deductions;
  const updatePassword = async () => { if (newPassword.length < 8 || newPassword !== confirmPassword) { setMessage('Use 8 or more characters and make both passwords match.'); return; } const { error } = await supabase.auth.updateUser({ password: newPassword }); setMessage(error?.message || 'Password updated successfully.'); if (!error) { setNewPassword(''); setConfirmPassword(''); } };
  const uploadPhoto = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setMessage('Uploading photo...'); const path = `${profile.id}.${file.name.split('.').pop() || 'jpg'}`; const { error } = await supabase.storage.from('avatars').upload(path, file, { upsert: true, contentType: file.type }); if (error) { setMessage(error.message); return; } const { data } = supabase.storage.from('avatars').getPublicUrl(path); const update = await supabase.from('profiles').update({ photo_url: data.publicUrl } as never).eq('id', profile.id); setMessage(update.error?.message || 'Photo updated successfully.'); };
  const tabs: Array<[Tab, string]> = [['resume', 'Resume'], ['private', 'Private Info'], ['salary', 'Salary Info'], ['security', 'Security']];
  return <div className="mx-auto max-w-5xl space-y-6">
    <div className="flex items-center justify-between"><Link href={backHref}><Button variant="ghost" size="sm" leftIcon={<ArrowLeft className="h-4 w-4" />}>{backLabel}</Button></Link><Badge variant={profile.role === 'admin' ? 'primary' : 'neutral'}><Shield className="h-3.5 w-3.5" />{profile.role === 'admin' ? 'HR Administrator' : 'Employee'}</Badge></div>
    <section className="rounded-2xl border border-surface-200 bg-white p-6 shadow-card"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><div className="relative"><div className="flex h-24 w-24 items-center justify-center rounded-full bg-brand-600 text-3xl font-bold text-white">{getInitials(profile.fullName)}</div><label aria-label="Change profile photo" className="absolute bottom-0 right-0 cursor-pointer rounded-full bg-brand-600 p-2 text-white shadow-lg"><Camera className="h-3.5 w-3.5" /><input type="file" accept="image/*" className="hidden" onChange={(event) => void uploadPhoto(event)} /></label></div><div className="grid flex-1 grid-cols-1 gap-5 sm:grid-cols-2"><div><h1 className="text-2xl font-bold text-surface-900">{profile.fullName}</h1><p className="mt-1 text-sm text-brand-600">{profile.designation}</p><p className="mt-3 flex items-center gap-2 text-xs text-surface-500"><Mail className="h-3.5 w-3.5" />{profile.email}</p><p className="mt-2 flex items-center gap-2 text-xs text-surface-500"><Phone className="h-3.5 w-3.5" />{profile.phone}</p></div><div className="space-y-2 text-xs text-surface-600"><p>Company: Dayflow</p><p>Department: {profile.department}</p><p>Location: Bangalore</p><p>Joined: {formatDate(profile.dateOfJoining)}</p></div></div></div></section>
    <nav className="flex gap-1 overflow-x-auto rounded-xl border border-surface-200 bg-white p-1 shadow-card">{tabs.map(([key, label]) => <button key={key} type="button" onClick={() => setTab(key)} className={`whitespace-nowrap rounded-lg px-4 py-2.5 text-xs font-semibold ${tab === key ? 'bg-brand-600 text-white' : 'text-surface-600 hover:bg-surface-100'}`}>{label}</button>)}</nav>
    {tab === 'resume' && <div className="grid gap-6 md:grid-cols-[1.4fr_1fr]"><Panel title="About"><p>{profile.fullName} is a {profile.designation} in the {profile.department} team.</p><p className="mt-4"><strong>What I love about my job</strong><br />Solving meaningful problems with a collaborative team.</p><p className="mt-4"><strong>Interests and hobbies</strong><br />Technology, design, and exploring Bangalore.</p></Panel><Panel title="Skills & Certification"><div className="flex flex-wrap gap-2"><Badge variant="primary">Communication</Badge><Badge variant="primary">Problem solving</Badge><Badge variant="primary">Teamwork</Badge></div><h3 className="mb-2 mt-6 font-semibold text-surface-900">Certification</h3><Badge>Professional certification</Badge></Panel></div>}
    {tab === 'private' && <div className="grid gap-6 md:grid-cols-2"><Panel title="Private Information"><Detail label="Date of Birth" value="Not provided" /><Detail label="Residing Address" value={profile.address} /><Detail label="Nationality" value="Indian" /><Detail label="Personal Email" value="Not provided" /><Detail label="Gender" value="Not provided" /><Detail label="Marital Status" value="Not provided" /></Panel><Panel title="Bank Details"><Detail label="Account Number" value="Not provided" /><Detail label="Bank Name" value="Not provided" /><Detail label="IFSC Code" value="Not provided" /><Detail label="PAN / UAN" value="Not provided" /><Detail label="Employee Code" value={profile.employeeId} /></Panel></div>}
    {tab === 'salary' && <Panel title="Salary Information"><div className="grid gap-4 sm:grid-cols-3"><Salary label="Month Wage" value={basic + allowances} /><Salary label="Yearly Wage" value={(basic + allowances) * 12} /><Salary label="Net Display" value={basic + allowances - deductions} /></div><div className="mt-6 divide-y divide-surface-100"><Detail label="Basic Salary" value={`${formatCurrency(basic)} / month`} /><Detail label="Allowances" value={`${formatCurrency(allowances)} / month`} /><Detail label="Deductions" value={`${formatCurrency(deductions)} / month`} /></div><p className="mt-4 text-xs text-surface-500">Read-only for employees. Administrators manage payroll separately.</p></Panel>}
    {tab === 'security' && <Panel title="Security"><div className="max-w-lg space-y-4"><label className="block text-xs font-medium text-surface-600">New password<input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-1 w-full rounded-lg border border-surface-200 px-3 py-2" /></label><label className="block text-xs font-medium text-surface-600">Confirm new password<input type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="mt-1 w-full rounded-lg border border-surface-200 px-3 py-2" /></label><Button variant="primary" leftIcon={<LockKeyhole className="h-4 w-4" />} onClick={() => void updatePassword()}>Update password</Button>{message && <p className="text-xs text-surface-500">{message}</p>}</div></Panel>}
  </div>;
}

function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-2xl border border-surface-200 bg-white p-6 text-sm text-surface-600 shadow-card"><h2 className="mb-5 border-b border-surface-100 pb-3 font-bold text-surface-900">{title}</h2>{children}</section>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="flex flex-wrap justify-between gap-3 py-2.5 text-xs"><span className="text-surface-500">{label}</span><span className="font-semibold text-surface-900">{value}</span></div>; }
function Salary({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-brand-50 p-4"><p className="text-xs text-brand-700">{label}</p><p className="mt-2 text-xl font-bold text-surface-900">{formatCurrency(value)}</p></div>; }
