'use client';

import { FormEvent, useState } from 'react';
import { UserPlus, X } from 'lucide-react';
import { Button } from '@/components/ui/Button';

export function CreateEmployee({ onCreated }: { onCreated: () => void }) {
  const [open, setOpen] = useState(false); const [form, setForm] = useState({ full_name: '', email: '', department: '', joining_date: new Date().toISOString().slice(0, 10) }); const [result, setResult] = useState<{ employeeId: string; temporaryPassword: string } | null>(null); const [error, setError] = useState('');
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); const response = await fetch('/api/employees', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) setError(data.error); else { setResult(data.employee); onCreated(); } };
  return <><Button variant="primary" onClick={() => { setOpen(true); setResult(null); }} leftIcon={<UserPlus className="h-4 w-4" />}>NEW</Button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl border border-surface-200 bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold text-surface-900">Create employee</h2><button onClick={() => setOpen(false)} aria-label="Close"><X className="h-5 w-5" /></button></div>{result ? <div className="mt-5 space-y-3"><p className="text-sm text-emerald-700">Employee created. Share these credentials securely.</p><div className="rounded-xl bg-surface-50 p-4 font-mono text-sm"><p>Login ID: {result.employeeId}</p><p>Temporary password: {result.temporaryPassword}</p></div><Button variant="primary" className="w-full" onClick={() => setOpen(false)}>Done</Button></div> : <form onSubmit={submit} className="mt-5 space-y-3"><input required placeholder="Full name" value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" /><input required type="email" placeholder="Work email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" /><input placeholder="Department" value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })} className="w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" /><label className="block text-xs text-surface-600">Joining date<input required type="date" value={form.joining_date} onChange={(event) => setForm({ ...form, joining_date: event.target.value })} className="mt-1 w-full rounded-lg border border-surface-200 px-3 py-2 text-sm" /></label>{error && <p className="text-sm text-rose-700">{error}</p>}<Button type="submit" variant="primary" className="w-full">Create and generate credentials</Button></form>}</div></div>}</>;
}